# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: '<a href="https://github.com/cdillond">github</a> <a href="https://ciaran.lol">homepage</a>'

markdown: kramdown
kramdown:
    math_engine: katex

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

